/**
 * execution — small-tier helpers for the /wb-execution phase.
 *
 * A planner subagent emits a phased task plan in a STRICT format; we parse it
 * deterministically (no model judgment in the parse), feed it to the beads tree
 * planner, then assemble tasks.md embedding the captured bead ids. Ref scheme
 * here mirrors planBeadsTree: phase i → `phase-i`, task j → `phase-i-task-j`.
 */

import type { Phase } from "./tools/beads.ts";

const PHASE_RE = /^###\s*Phase:\s*(.+?)\s*$/;
const TASK_RE = /^[-*]\s+(?:\[.\]\s+)?(.+?)\s*$/;

/** Parse the strict planner output into phases. Prose and other lines are ignored. */
export function parseTaskPlan(md: string): Phase[] {
  const phases: Phase[] = [];
  let current: Phase | undefined;
  for (const line of md.split("\n")) {
    const p = line.match(PHASE_RE);
    if (p) {
      current = { name: p[1], tasks: [] };
      phases.push(current);
      continue;
    }
    const t = line.match(TASK_RE);
    if (t && current) current.tasks.push(t[1]);
  }
  return phases.filter((ph) => ph.tasks.length > 0);
}

/** Assemble tasks.md body, embedding bead ids from the ref→id map. */
export function assembleTasksBody(epicTitle: string, phases: Phase[], refToId: Record<string, string>): string {
  const id = (ref: string) => (refToId[ref] ? ` (\`${refToId[ref]}\`)` : "");
  const parts = [
    `# Tasks: ${epicTitle}`,
    "",
    "> STEPS ONLY. Beads tracks status; the checkboxes here are documentation.",
    `Epic: ${refToId["epic"] ? `\`${refToId["epic"]}\`` : "(not created)"}`,
    "",
  ];
  phases.forEach((phase, pi) => {
    parts.push(`## Phase ${pi + 1}: ${phase.name}${id(`phase-${pi + 1}`)}`, "");
    phase.tasks.forEach((task, ti) => {
      parts.push(`- [ ] ${task}${id(`phase-${pi + 1}-task-${ti + 1}`)}`);
    });
    parts.push("");
  });
  parts.push("---", "_Generated by `/wb-execution`. Work it with `/wb-implement` (beads = source of truth)._");
  return parts.join("\n") + "\n";
}
