/**
 * orchestrator — small-tier control flow for the research phase.
 *
 * The thesis of the small tier: the model does its work in tiny, scoped subagent
 * calls (locator / analyzer / pattern), and the EXTENSION deterministically
 * assembles the artifact. There is no large-model synthesis step to get wrong —
 * research.md is composed from the subagents' verbatim, structured findings.
 *
 * This module holds the pure, testable cores. The spawn wiring lives in index.ts.
 */

const DATE_PREFIX = /^\d{4}-\d{2}-\d{2}-/;

/**
 * Find every tasks.md in the repo (location-independent — plans aren't always under
 * docs/plans/). `repoFiles` is a repo-relative file list (e.g. from git ls-files).
 */
export function discoverTasksPaths(repoFiles: string[]): string[] {
  return repoFiles.filter((p) => p === "tasks.md" || p.endsWith("/tasks.md")).sort();
}

/**
 * Narrow discovered tasks.md paths by a selector: exact path match wins, else
 * substring. Empty selector returns all (caller decides sole-vs-ambiguous).
 */
export function matchTasksPaths(paths: string[], selector: string): string[] {
  const s = selector.trim();
  if (!s) return paths;
  const exact = paths.filter((p) => p === s);
  return exact.length ? exact : paths.filter((p) => p.includes(s));
}

/**
 * Choose which plan directory to operate on. With an arg, the first dir whose
 * name contains it; otherwise the latest (date-prefixed names sort chronologically).
 */
export function pickPlanDir(dirNames: string[], arg?: string): string | undefined {
  const plans = dirNames.filter((d) => DATE_PREFIX.test(d));
  if (arg && arg.trim()) {
    const needle = arg.trim();
    return plans.find((d) => d.includes(needle));
  }
  if (plans.length === 0) return undefined;
  return [...plans].sort().at(-1);
}

export interface ResearchSection {
  heading: string;
  body: string;
}

/**
 * Agents emit their own top-level heading (e.g. "## Locations for: <topic>").
 * The assembler adds an attributed heading per section, so drop the agent's
 * leading heading to avoid stacking two headings.
 */
export function stripLeadingHeading(body: string): string {
  const trimmed = body.trim();
  if (!trimmed.startsWith("#")) return trimmed;
  const nl = trimmed.indexOf("\n");
  return nl === -1 ? "" : trimmed.slice(nl + 1).trim();
}

/** Compose the FACTS-ONLY research body from subagent findings. */
export function assembleResearchBody(topic: string, sections: ResearchSection[]): string {
  const parts = [
    `# Research: ${topic}`,
    "",
    "> FACTS ONLY — assembled deterministically from scoped research agents. " +
      "Each section is that agent's verbatim findings; review and refine before relying on it.",
    "",
  ];
  for (const s of sections) {
    parts.push(`## ${s.heading}`, "", stripLeadingHeading(s.body) || "_(no findings)_", "");
  }
  parts.push("---", "_Generated by `/wb-research` (tier: small)._");
  return parts.join("\n") + "\n";
}

/**
 * Compose a design.md DRAFT for the small tier: gathered context from research
 * agents, followed by an explicit decisions checklist the human fills in. Design
 * judgment stays with the human; the extension only assembles context + prompts.
 */
export function assembleDesignDraft(topic: string, sections: ResearchSection[]): string {
  const parts = [
    `# Design: ${topic}`,
    "",
    "> DECISIONS (WHAT / WHY). Draft — gathered context below; you make the calls in Decisions.",
    "",
    "## Decisions (fill in)",
    "",
    "- [ ] **What** are we building? (one paragraph)",
    "- [ ] **Why** this approach over alternatives?",
    "- [ ] **Alternatives** considered and rejected (and why)?",
    "- [ ] **Risks / unknowns** and how we'll handle them?",
    "- [ ] **Out of scope** (explicitly)?",
    "",
  ];
  for (const s of sections) {
    parts.push(`## Context: ${s.heading}`, "", stripLeadingHeading(s.body) || "_(no findings)_", "");
  }
  parts.push("---", "_Scaffolded by `/wb-design` (tier: small). Fill the Decisions, then `/wb-execution`._");
  return parts.join("\n") + "\n";
}

/**
 * In-pipeline research validation: append a warning section listing cited paths that
 * were not found in the repo (likely hallucinations). Deterministic port of the
 * original workbench's post-write research-validator — path grounding is qwen's #1
 * failure, so research must be checked, not trusted. No-op when everything grounds.
 */
export function annotateUngrounded(body: string, missing: string[]): string {
  if (missing.length === 0) return body;
  const lines = [
    body.trimEnd(),
    "",
    "## ⚠️ Unverified citations",
    "",
    "These cited paths were NOT found in the repo and may be hallucinated — verify or remove:",
    ...missing.map((p) => `- \`${p}\``),
    "",
  ];
  return lines.join("\n") + "\n";
}

/**
 * Replace a markdown file's body while preserving its YAML frontmatter, flipping
 * only the `status:` line. If there is no frontmatter, returns just the new body.
 */
export function setStatusAndReplaceBody(existing: string, status: string, newBody: string): string {
  const m = existing.match(/^(---\n[\s\S]*?\n---\n)/);
  if (!m) return newBody;
  const frontmatter = m[1].replace(/^status:.*$/m, `status: ${status}`);
  return `${frontmatter}\n${newBody}`;
}
