/**
 * orchestrator — small-tier control flow for the research phase.
 *
 * The thesis of the small tier: the model does its work in tiny, scoped subagent
 * calls (locator / analyzer / pattern), and the EXTENSION deterministically
 * assembles the artifact. There is no large-model synthesis step to get wrong —
 * research.md is composed from the subagents' verbatim, structured findings.
 *
 * This module holds the pure, testable cores. The spawn wiring lives in index.ts.
 */

const DATE_PREFIX = /^\d{4}-\d{2}-\d{2}-/;

/**
 * Choose which plan directory to operate on. With an arg, the first dir whose
 * name contains it; otherwise the latest (date-prefixed names sort chronologically).
 */
export function pickPlanDir(dirNames: string[], arg?: string): string | undefined {
  const plans = dirNames.filter((d) => DATE_PREFIX.test(d));
  if (arg && arg.trim()) {
    const needle = arg.trim();
    return plans.find((d) => d.includes(needle));
  }
  if (plans.length === 0) return undefined;
  return [...plans].sort().at(-1);
}

export interface ResearchSection {
  heading: string;
  body: string;
}

/** Compose the FACTS-ONLY research body from subagent findings. */
export function assembleResearchBody(topic: string, sections: ResearchSection[]): string {
  const parts = [
    `# Research: ${topic}`,
    "",
    "> FACTS ONLY — assembled deterministically from scoped research agents. " +
      "Each section is that agent's verbatim findings; review and refine before relying on it.",
    "",
  ];
  for (const s of sections) {
    parts.push(`## ${s.heading}`, "", s.body.trim() || "_(no findings)_", "");
  }
  parts.push("---", "_Generated by `/wb-research` (tier: small)._");
  return parts.join("\n") + "\n";
}

/**
 * Replace a markdown file's body while preserving its YAML frontmatter, flipping
 * only the `status:` line. If there is no frontmatter, returns just the new body.
 */
export function setStatusAndReplaceBody(existing: string, status: string, newBody: string): string {
  const m = existing.match(/^(---\n[\s\S]*?\n---\n)/);
  if (!m) return newBody;
  const frontmatter = m[1].replace(/^status:.*$/m, `status: ${status}`);
  return `${frontmatter}\n${newBody}`;
}
